# Generated by Django 3.1.7 on 2021-02-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.unit'),
        ),
    ]
